#include "ImagePreprocessing.h"

#include <opencv2/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>

#include <filesystem>

namespace fs = std::filesystem;

void ImagePreprocessing::checkOutputFilePath(const std::string& preprocessImagePath) const
{
    if (fs::exists(preprocessImagePath)) {
        if (!fs::is_directory(preprocessImagePath)) {
            throw std::runtime_error("Output path exists but is not a directory.");
        }
    }

    if (!fs::create_directory(preprocessImagePath)) {
        throw std::runtime_error("Unable to create output directory.");
    }
}


void ImagePreprocessing::validateInputFilePath(const std::string &rawPngPath) const{
    if (!fs::exists(rawPngPath) || !fs::is_directory(rawPngPath)) {
        throw std::runtime_error("Raw PNG path does not exist or is not a directory.");
    }
}

void ImagePreprocessing::getAllRawImageNames(const std::string &rawPngPath)  {

    validateInputFilePath(rawPngPath);

    rawPngPaths.clear();

    // Load files from rawPngPath into paths
    for (const auto& entry : std::filesystem::directory_iterator(rawPngPath)) {
        
        if (entry.is_regular_file() && entry.path().extension() == ".png") {
            rawPngPaths.push_back(entry.path().string());
        }
    }

    std::sort(rawPngPaths.begin(), rawPngPaths.end());
}

/**
 * @brief Orchestrates the complete image preprocessing pipeline.
 *
 * Loads a raw image from disk, applies all preprocessing steps
 * (noise removal, contrast enhancement, deskewing, non-text removal),
 * and saves the final OCR-ready image to disk.
 *
 * @param rawFilePath Path to the raw PNG image generated by Poppler.
 * @param preprocessedImagePath Path where the preprocessed image
 *        will be written.
 *
 * @note This method guarantees that the output image is suitable
 *       for OCR engines (binary, deskewed, high-contrast).
 */
void ImagePreprocessing::preprocess(const std::string & rawFilePath, const std::string & preprocessImagePath){
    
    getAllRawImageNames(rawFilePath);

    checkOutputFilePath(preprocessImagePath);

    for(auto &file : rawPngPaths){

        cv::Mat image = cv::imread(file);
        
        if (image.empty()) {
            throw std::runtime_error("Failed to load image: " + file);
        }

        image = removeNoiseAndBackground(image);
        image = improveTextContrast(image);
        image = normalizeOrientationAndScale(image);
        image = separateTextFromNonText(image);

        std::filesystem::path inputPath(file);
        std::filesystem::path outputPath = std::filesystem::path(preprocessImagePath) / inputPath.filename();

        if (!cv::imwrite(outputPath.string(), image)) {
            throw std::runtime_error("Failed to write image: " + outputPath.string());
        }
    }
}

 /**
 * @brief Removes scanner noise and normalizes the background.
 *
 * Converts the input image to grayscale (if required), removes
 * salt-and-pepper noise, and suppresses background variations
 * caused by uneven lighting or paper texture.
 *
 * @param inputImage Raw input image (RGB or grayscale).
 *
 * @return Grayscale image with reduced noise and normalized background.
 *
 * @pre inputImage must be a valid, non-empty image.
 * @post Output image is guaranteed to be single-channel (grayscale).
 */
cv::Mat ImagePreprocessing::removeNoiseAndBackground(const cv::Mat& inputImage){

    cv::Mat gray;
    cv::Mat denoised;
    cv::Mat backgroundReduced;

    // 1. Convert to grayscale if needed
    if (inputImage.channels() == 3) {
        cv::cvtColor(inputImage, gray, cv::COLOR_BGR2GRAY);
    } else {
        gray = inputImage.clone();
    }

    // 2. Remove salt-and-pepper noise
    cv::medianBlur(gray, denoised, 3);

    // 3. Reduce background variations (uneven illumination)
    // Using Gaussian blur to estimate background
    cv::Mat background;
    cv::GaussianBlur(denoised, background, cv::Size(31, 31), 0);

    // 4. Subtract background to enhance text
    cv::Mat diff;
    cv::absdiff(denoised, background, diff);

    // 5. Normalize result to full grayscale range
    cv::normalize(diff, backgroundReduced, 0, 255, cv::NORM_MINMAX);

    return backgroundReduced;

}

/**
 * @brief Enhances text contrast by converting the image to binary form.
 *
 * Applies adaptive thresholding to the input grayscale image to
 * separate foreground text from background, producing a
 * high-contrast binary image suitable for OCR.
 *
 * @param inputImage Grayscale image produced by
 *        removeNoiseAndBackground().
 *
 * @return Binary image where text pixels are highlighted and
 *         background pixels are suppressed.
 *
 * @pre inputImage must be a single-channel grayscale image.
 * @post Output image is a binary image (black and white).
 */
cv::Mat ImagePreprocessing::improveTextContrast(const cv::Mat& inputImage)
{
    cv::Mat gray;
    cv::Mat binary;

    // 1. Ensure grayscale input
    if (inputImage.channels() == 3) {
        cv::cvtColor(inputImage, gray, cv::COLOR_BGR2GRAY);
    } else {
        gray = inputImage.clone();
    }

    // 2. Apply adaptive thresholding
    // Works well for uneven lighting and old scanned documents
    cv::adaptiveThreshold(
        gray,
        binary,
        255,
        cv::ADAPTIVE_THRESH_GAUSSIAN_C,
        cv::THRESH_BINARY,
        31,   // block size (must be odd)
        10    // constant subtracted from mean
    );

    return binary;
}

/**
 * @brief Corrects image skew and normalizes scale for OCR.
 *
 * Detects the dominant text orientation and rotates the image
 * to make text lines horizontal. Optionally rescales the image
 * to ensure character sizes are suitable for OCR engines
 * (approximately 300 DPI equivalent).
 *
 * @param inputImage Binary image produced by improveTextContrast().
 *
 * @return Deskewed and scale-normalized binary image.
 *
 * @pre inputImage must be a binary image.
 * @post Output image is binary, deskewed, and OCR-friendly.
 */
cv::Mat ImagePreprocessing::normalizeOrientationAndScale(const cv::Mat& inputImage)
{
    cv::Mat inverted;
    cv::bitwise_not(inputImage, inverted);

    // 1. Find all non-zero points (text pixels)
    std::vector<cv::Point> points;
    cv::findNonZero(inverted, points);

    // If no text detected, return original
    if (points.empty()) {
        return inputImage.clone();
    }

    // 2. Compute minimum area bounding box
    cv::RotatedRect box = cv::minAreaRect(points);

    double angle = box.angle;

    // minAreaRect angle correction
    if (angle < -45.0) {
        angle += 90.0;
    }

    // 3. Rotate image to deskew
    cv::Mat rotated;
    cv::Point2f center(inputImage.cols / 2.0f, inputImage.rows / 2.0f);

    cv::Mat rotationMatrix =
        cv::getRotationMatrix2D(center, angle, 1.0);

    cv::warpAffine(
        inputImage,
        rotated,
        rotationMatrix,
        inputImage.size(),
        cv::INTER_CUBIC,
        cv::BORDER_REPLICATE
    );

    // 4. Scale normalization (optional but recommended)
    // Target: character height roughly OCR-friendly
    const int targetWidth = 2480;  // ~A4 at 300 DPI
    if (rotated.cols < targetWidth) {
        double scale = static_cast<double>(targetWidth) / rotated.cols;
        cv::resize(rotated, rotated, cv::Size(), scale, scale, cv::INTER_CUBIC);
    }

    return rotated;
}


/**
 * @brief Suppresses non-text elements from the image.
 *
 * Identifies and removes obvious non-text regions such as
 * page borders, large logos, decorative graphics, and
 * scanner artifacts while preserving textual content.
 *
 * @param inputImage Binary, deskewed image produced by
 *        normalizeOrientationAndScale().
 *
 * @return Binary image dominated by text regions, with most
 *         non-text elements removed or suppressed.
 *
 * @pre inputImage must be binary and deskewed.
 * @post Output image is optimized for OCR text recognition.
 */
cv::Mat ImagePreprocessing::separateTextFromNonText(const cv::Mat& inputImage)
{
    cv::Mat cleaned = inputImage.clone();

    std::vector<std::vector<cv::Point>> contours;
    std::vector<cv::Vec4i> hierarchy;

    // 1. Find contours (connected components)
    cv::findContours(
        cleaned,
        contours,
        hierarchy,
        cv::RETR_EXTERNAL,
        cv::CHAIN_APPROX_SIMPLE
    );

    const int imageArea = cleaned.rows * cleaned.cols;

    // 2. Filter non-text regions
    for (const auto& contour : contours) {
        cv::Rect box = cv::boundingRect(contour);
        int area = box.area();

        // Heuristic filters
        bool isTooLarge = area > imageArea * 0.20;   // logos, big images
        bool isTooSmall = area < 30;                 // noise
        bool isTooWide = box.width > cleaned.cols * 0.9; // page border lines

        if (isTooLarge || isTooSmall || isTooWide) {
            // Remove non-text region
            cv::rectangle(cleaned, box, cv::Scalar(0), cv::FILLED);
        }
    }

    return cleaned;
}